export const state = {
  map: null,
  markers: [],
  markerRegistry: new Map(),
  selectedPubId: null,
  checkins: {},
  pubMessages: {},
  markerCluster: null,
  currentUser: null,
  currentFilterType: 'all',
  currentSearchQuery: '',
  isSidebarHidden: false,
  isListOnly: false,
  friendVisitData: {},
  isComparing: false,
  isAdmin: false,
  isSuperadmin: false,
  lastNicknameChange: null,
  lastFriendCodeChange: null,
  userLocationMarker: null
};